### ISSUE TITLE
Change Renders to use Engines rather than Types

### ISSUE THREAD

**Issue by danhanly** [danhanly/notifly#1]
Instead of showing `Error` renderers, `Info` renderers, it may be necessary to make `error` and `info` etc. methods of a single Renderer. Similar to how Drivers work, where it's all packages on a per system basis.

examples:
`BootstrapRenderer`
`TwigRenderer`

Need a way of clearly allowing method variations and expansions whilst still retaining Interface driven classes

**Comment by danhanly** [comment]
@matiit I've expended test coverage now and cleaned it all up. I left out extensively testing the renderers for the purpose of this issue. Pointless testing it if it's going to be changed anyway.

There will be some tests that need reworking after this, those which load the configuration (which will undoubtedly be changed)

**Comment by matiit** [comment]
Ok, it makes sense not to write tests for something that will be changed anyway.

Let me rewrite this to be Engine-alike. I'll spend some time on this todays' evening.

**Comment by danhanly** [comment]
+1

Make sure you get my changes from last night/this morning into your fork. I've tested everything using `@covers`

**Comment by matiit** [comment]
@danhanly https://github.com/danhanly/notifly/pull/4
